---
name: JSII Publish
description: Builds and publishes JSII packages
author: deemes79@googlemail.com
branding:
  icon: upload-cloud
  color: orange
runs:
  using: docker
  image: docker://udondan/jsii-publish:0.6.2
inputs:
  BUILD_SOURCE:
    description: Indicates if the source should be build (tsc)
    default: false
  BUILD_PACKAGES:
    description: Indicates if the packages should be build (jsii)
    default: false
  VERSION:
    description: If set, the version in `package.json` will be updated with this value
    required: false
  NPM_TOKEN:
    description: Your publish token for npm. If passed, package will be published to npm
    required: false
  PYPI_TOKEN:
    description: Your publish token for PyPI. If passed, package will be published to PyPI
    required: false
  NUGET_TOKEN:
    description: Your publish token for NuGet. If passed, package will be published to NuGet
    required: false
