---
name: JSII Publish
description: Builds and publishes JSII packages
author: deemes79@googlemail.com
branding:
  icon: upload-cloud
  color: orange
runs:
  using: docker
  image: docker://udondan/jsii-publish:0.3.0
inputs:
  NPM_TOKEN:
    description: NPM Token for publishing
    required: false
  NPM_PUBLISH:
    description: Indicates if the package should be published to NPM
    required: false
