---
name: JSII Publish
description: Builds and publishes JSII packages
author: deemes79@googlemail.com
branding:
  icon: upload-cloud
  color: orange
runs:
  using: docker
  image: docker://udondan/jsii-publish:0.3.0
inputs:
  NPM_TOKEN:
    description: npm Token for publishing
    required: false
  PYPI_TOKEN:
    description: PyPI Token for publishing
    required: false
